### ISSUE TITLE
error message when running this action

### ISSUE THREAD

**Issue by renperez-cpi** [omegion/argocd-actions#11]
actions runner unable to pull this repository. 
Unable to resolve actions. Repository not found : omegion/argocd-app-actions.

**Comment by RossComputerGuy** [comment]
I get a similar error message:
```
 Unable to find image 'ghcr.io/omegion/argocd-actions:master' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

**Comment by RossComputerGuy** [comment]
https://github.com/MidstallSoftware/vista/commit/5c263a0530399dbac660799fa6c94f94db665d94 That didn't work

**Comment by tony-hadjiivanov** [comment]
@RossComputerGuy I see that you use `omegion/argocd-app-actions` where it should be `omegion/argocd-actions` - try that

**Comment by omegion** [comment]
This is fixed with https://github.com/omegion/argocd-actions/pull/19. Please read the updated  README for more details.
